version: "3.9"

services:
  minecraft-web:
    build:
      context: https://github.com/fruitcake514/minecraft-in-docker.git
    container_name: minecraft-in-docker
    restart: unless-stopped

    ports:
      - "8080:8080/tcp"  # noVNC web access
      - "25565:25565/udp"

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago

      - DISPLAY=:0
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - PULSE_SERVER=unix:/tmp/pulse/native

      - MC_INSTANCE=Vanilla
      - MESA_LOADER_DRIVER_OVERRIDE=iris
      - LIBGL_ALWAYS_SOFTWARE=0
      - __GLX_VENDOR_LIBRARY_NAME=mesa
      - vblank_mode=0

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

    group_add:
      - "44"
      - "109"

    shm_size: "4gb"

    volumes:
      - ./data/prism:/home/gamer/.local/share/PrismLauncher
      - ./data/minecraft:/home/gamer/.minecraft

    security_opt:
      - seccomp=unconfined

    cap_add:
      - SYS_ADMIN

    tmpfs:
      - /tmp:size=2g
      - /run:size=256m
