min_log_level = 2
port = 47989
address_family = both
upnp = disabled
origin_web_ui_allowed = pc
ping_timeout = 10000
lan_encryption_mode = 0
wan_encryption_mode = 1
file_apps = /home/gamer/.config/sunshine/apps.json
